# Generated by Django 4.2.3 on 2024-06-10 17:56

from django.db import migrations, models
import django.db.models.deletion
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="news.user",
                validators=[news.validators.validate_empty_field],
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(
                validators=[news.validators.validate_empty_field]
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[
                    news.validators.validate_title,
                    news.validators.validate_empty_field,
                ],
            ),
        ),
    ]
